/*
###############################################################
#  Generated by:      Cadence Innovus 21.14-s109_1
#  OS:                Linux x86_64(Host ID nanodc.iitgn.ac.in)
#  Generated on:      Fri Jul 17 11:04:37 2026
#  Design:            pqc_top_wrapper
#  Command:           saveNetlist -includePowerGround ./ClockTreeSynthesis/top_chip_wrapper_pqc_postCTS_withPG.v
###############################################################
*/
module buffd1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dl03d1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dfcrq1 (
	CDN, 
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module decrq1 (
	CDN, 
	CP, 
	D, 
	ENN, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   input ENN;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module nd02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oan211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oai21d1 (
	A, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nr03d1 (
	A1, 
	A2, 
	A3, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoim211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd03d1 (
	A1, 
	A2, 
	A3, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module inv0d1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfcrb1 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module pc3c01 (
	CCLK, 
	CP, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input CCLK;
   output CP;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3d01 (
	PAD, 
	CIN, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input PAD;
   output CIN;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvdi (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   inout VDDO;
   output VDD;
endmodule

module pv0i (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   output VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvda (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   output VDDO;
   inout VDD;
endmodule

module pv0a (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   output VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3o01 (
	I, 
	PAD, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input I;
   output PAD;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 17 2026 07:38:40 EDT (Jul 17 2026 11:38:40 UTC)
// Verification Directory fv/pqc_top_wrapper 
module fpga_wrapper (
	clk, 
	rst_n, 
	start, 
	sw, 
	led, 
	done_led, 
	VDD_CORE, 
	VSS_CORE);
   input clk;
   input rst_n;
   input start;
   input [3:0] sw;
   output [3:0] led;
   output done_led;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN11_rst_n_pad;
   wire FE_PHN10_n_9;
   wire FE_PHN9_n_8;
   wire FE_PHN8_n_4;
   wire FE_PHN7_rst_n_pad;
   wire FE_PHN6_sw_pad_0;
   wire FE_PHN5_sw_pad_1;
   wire FE_PHN4_sw_pad_3;
   wire FE_PHN3_sw_pad_2;
   wire FE_PHN2_n_2;
   wire FE_PHN1_uut_state_2;
   wire FE_PHN0_n_1;
   wire [2:0] uut_state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;

   // Module instantiations
   buffd1 FE_PHC11_rst_n_pad (
	.I(FE_PHN7_rst_n_pad),
	.Z(FE_PHN11_rst_n_pad), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC10_n_9 (
	.I(n_9),
	.Z(FE_PHN10_n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC9_n_8 (
	.I(n_8),
	.Z(FE_PHN9_n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC8_n_4 (
	.I(n_4),
	.Z(FE_PHN8_n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC7_rst_n_pad (
	.I(rst_n),
	.Z(FE_PHN7_rst_n_pad), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC6_sw_pad_0 (
	.I(sw[0]),
	.Z(FE_PHN6_sw_pad_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC5_sw_pad_1 (
	.I(sw[1]),
	.Z(FE_PHN5_sw_pad_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC4_sw_pad_3 (
	.I(sw[3]),
	.Z(FE_PHN4_sw_pad_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC3_sw_pad_2 (
	.I(sw[2]),
	.Z(FE_PHN3_sw_pad_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC2_n_2 (
	.I(n_2),
	.Z(FE_PHN2_n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC1_uut_state_2 (
	.I(uut_state[2]),
	.Z(FE_PHN1_uut_state_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC0_n_1 (
	.I(n_1),
	.Z(FE_PHN0_n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 uut_valid_out_reg (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN10_n_9),
	.Q(done_led), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \uut_M_OUT_REAL_reg[3]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN4_sw_pad_3),
	.ENN(n_5),
	.Q(led[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \uut_M_OUT_REAL_reg[0]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN6_sw_pad_0),
	.ENN(n_5),
	.Q(led[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \uut_M_OUT_REAL_reg[1]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN5_sw_pad_1),
	.ENN(n_5),
	.Q(led[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g266__2398 (
	.A1(n_5),
	.A2(n_7),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \uut_M_OUT_REAL_reg[2]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN3_sw_pad_2),
	.ENN(n_5),
	.Q(led[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g269__5107 (
	.A(FE_PHN1_uut_state_2),
	.B(n_3),
	.C1(FE_PHN0_n_1),
	.C2(uut_state[1]),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai21d1 g270__6260 (
	.A(done_led),
	.B1(uut_state[0]),
	.B2(uut_state[1]),
	.ZN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \uut_state_reg[2]  (
	.CDN(n_0),
	.CP(clk),
	.D(n_6),
	.Q(uut_state[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr03d1 g273__4319 (
	.A1(FE_PHN2_n_2),
	.A2(FE_PHN1_uut_state_2),
	.A3(FE_PHN0_n_1),
	.ZN(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim211d1 g274__8428 (
	.A(uut_state[0]),
	.B(FE_PHN1_uut_state_2),
	.C1(uut_state[1]),
	.C2(start),
	.ZN(n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd03d1 g275__5526 (
	.A1(FE_PHN0_n_1),
	.A2(FE_PHN2_n_2),
	.A3(FE_PHN1_uut_state_2),
	.ZN(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g276__6783 (
	.A1(FE_PHN0_n_1),
	.A2(uut_state[1]),
	.ZN(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d1 g279 (
	.I(FE_PHN11_rst_n_pad),
	.ZN(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \uut_state_reg[1]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN9_n_8),
	.Q(uut_state[1]),
	.QN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \uut_state_reg[0]  (
	.CDN(n_0),
	.CP(clk),
	.D(FE_PHN8_n_4),
	.Q(uut_state[0]),
	.QN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module pqc_top_wrapper (
	clk, 
	rst_n, 
	start, 
	sw, 
	led, 
	done_led);
   input clk;
   input rst_n;
   input start;
   input [3:0] sw;
   output [3:0] led;
   output done_led;

   // Internal wires
   wire [3:0] sw_pad;
   wire [3:0] led_pad;
   wire clk_buf;
   wire clk_pad;
   wire done_led_pad;
   wire rst_n_pad;
   wire start_pad;
   wire VDD_CORE;
   wire VSS_CORE;
   wire VDDO_CORE;
   wire VSSO_CORE;

   // Module instantiations
   fpga_wrapper uut (
	.clk(clk_buf),
	.rst_n(rst_n_pad),
	.start(start_pad),
	.sw(sw_pad),
	.led(led_pad),
	.done_led(done_led_pad), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   pc3c01 pc3c01_clk_buf (
	.CCLK(clk_pad),
	.CP(clk_buf), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_clk (
	.PAD(clk),
	.CIN(clk_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_rst_n (
	.PAD(rst_n),
	.CIN(rst_n_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_start (
	.PAD(start),
	.CIN(start_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_sw0 (
	.PAD(sw[0]),
	.CIN(sw_pad[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_sw1 (
	.PAD(sw[1]),
	.CIN(sw_pad[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_sw2 (
	.PAD(sw[2]),
	.CIN(sw_pad[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_sw3 (
	.PAD(sw[3]),
	.CIN(sw_pad[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_0 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_dummy3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_done_led (
	.I(done_led_pad),
	.PAD(done_led), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_led0 (
	.I(led_pad[0]),
	.PAD(led[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_led1 (
	.I(led_pad[1]),
	.PAD(led[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_led2 (
	.I(led_pad[2]),
	.PAD(led[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o01 pc3o01_led3 (
	.I(led_pad[3]),
	.PAD(led[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
endmodule

