###############################################################
#  Generated by:      Cadence Innovus 21.14-s109_1
#  OS:                Linux x86_64(Host ID nanodc.iitgn.ac.in)
#  Generated on:      Fri Jul 17 11:04:37 2026
#  Design:            pqc_top_wrapper
###############################################################
current_design pqc_top_wrapper
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_propagated_clock  [get_ports {clk}]
set_wire_load_mode enclosed
set_clock_uncertainty 1 [get_clocks {clk}]
set_clock_latency -source -early -min -rise  -0.885686 [get_ports {clk}] -clock clk 
set_clock_latency -source -early -min -fall  -1.43331 [get_ports {clk}] -clock clk 
set_clock_latency -source -early -max -rise  -0.885686 [get_ports {clk}] -clock clk 
set_clock_latency -source -early -max -fall  -1.43331 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -min -rise  -0.885686 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -min -fall  -1.43331 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -max -rise  -0.885686 [get_ports {clk}] -clock clk 
set_clock_latency -source -late -max -fall  -1.43331 [get_ports {clk}] -clock clk 
