
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 17 2026 07:38:40 EDT (Jul 17 2026 11:38:40 UTC)

// Verification Directory fv/pqc_top_wrapper 

module fpga_wrapper(clk, rst_n, start, sw, led, done_led);
  input clk, rst_n, start;
  input [3:0] sw;
  output [3:0] led;
  output done_led;
  wire clk, rst_n, start;
  wire [3:0] sw;
  wire [3:0] led;
  wire done_led;
  wire [2:0] uut_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  dfcrq1 uut_valid_out_reg(.CDN (n_0), .CP (clk), .D (n_9), .Q
       (done_led));
  decrq1 \uut_M_OUT_REAL_reg[3] (.CDN (n_0), .CP (clk), .D (sw[3]),
       .ENN (n_5), .Q (led[3]));
  decrq1 \uut_M_OUT_REAL_reg[0] (.CDN (n_0), .CP (clk), .D (sw[0]),
       .ENN (n_5), .Q (led[0]));
  decrq1 \uut_M_OUT_REAL_reg[1] (.CDN (n_0), .CP (clk), .D (sw[1]),
       .ENN (n_5), .Q (led[1]));
  nd02d1 g266__2398(.A1 (n_5), .A2 (n_7), .ZN (n_9));
  decrq1 \uut_M_OUT_REAL_reg[2] (.CDN (n_0), .CP (clk), .D (sw[2]),
       .ENN (n_5), .Q (led[2]));
  oan211d1 g269__5107(.A (uut_state[2]), .B (n_3), .C1 (n_1), .C2
       (uut_state[1]), .ZN (n_8));
  oai21d1 g270__6260(.A (done_led), .B1 (uut_state[0]), .B2
       (uut_state[1]), .ZN (n_7));
  dfcrq1 \uut_state_reg[2] (.CDN (n_0), .CP (clk), .D (n_6), .Q
       (uut_state[2]));
  nr03d1 g273__4319(.A1 (n_2), .A2 (uut_state[2]), .A3 (n_1), .ZN
       (n_6));
  aoim211d1 g274__8428(.A (uut_state[0]), .B (uut_state[2]), .C1
       (uut_state[1]), .C2 (start), .ZN (n_4));
  nd03d1 g275__5526(.A1 (n_1), .A2 (n_2), .A3 (uut_state[2]), .ZN
       (n_5));
  nd02d1 g276__6783(.A1 (n_1), .A2 (uut_state[1]), .ZN (n_3));
  inv0d0 g279(.I (rst_n), .ZN (n_0));
  dfcrb1 \uut_state_reg[1] (.CDN (n_0), .CP (clk), .D (n_8), .Q
       (uut_state[1]), .QN (n_2));
  dfcrb1 \uut_state_reg[0] (.CDN (n_0), .CP (clk), .D (n_4), .Q
       (uut_state[0]), .QN (n_1));
endmodule

module pqc_top_wrapper(clk, rst_n, start, sw, led, done_led);
  input clk, rst_n, start;
  input [3:0] sw;
  output [3:0] led;
  output done_led;
  wire clk, rst_n, start;
  wire [3:0] sw;
  wire [3:0] led;
  wire done_led;
  wire [3:0] sw_pad;
  wire [3:0] led_pad;
  wire clk_buf, clk_pad, done_led_pad, rst_n_pad, start_pad;
  fpga_wrapper uut(.clk (clk_buf), .rst_n (rst_n_pad), .start
       (start_pad), .sw (sw_pad), .led (led_pad), .done_led
       (done_led_pad));
  pc3c01 pc3c01_clk_buf(.CCLK (clk_pad), .CP (clk_buf));
  pc3d01 pc3d01_clk(.PAD (clk), .CIN (clk_pad));
  pc3d01 pc3d01_rst_n(.PAD (rst_n), .CIN (rst_n_pad));
  pc3d01 pc3d01_start(.PAD (start), .CIN (start_pad));
  pc3d01 pc3d01_sw0(.PAD (sw[0]), .CIN (sw_pad[0]));
  pc3d01 pc3d01_sw1(.PAD (sw[1]), .CIN (sw_pad[1]));
  pc3d01 pc3d01_sw2(.PAD (sw[2]), .CIN (sw_pad[2]));
  pc3d01 pc3d01_sw3(.PAD (sw[3]), .CIN (sw_pad[3]));
  pc3o01 pc3o01_done_led(.I (done_led_pad), .PAD (done_led));
  pc3o01 pc3o01_led0(.I (led_pad[0]), .PAD (led[0]));
  pc3o01 pc3o01_led1(.I (led_pad[1]), .PAD (led[1]));
  pc3o01 pc3o01_led2(.I (led_pad[2]), .PAD (led[2]));
  pc3o01 pc3o01_led3(.I (led_pad[3]), .PAD (led[3]));
endmodule

