###############################################################
#  Generated by:      Cadence Innovus 21.14-s109_1
#  OS:                Linux x86_64(Host ID nanodc.iitgn.ac.in)
#  Generated on:      Fri Jul 17 11:04:06 2026
#  Design:            pqc_top_wrapper
#  Command:           set_analysis_view -setup {worst} -hold {best}
###############################################################
current_design pqc_top_wrapper
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_wire_load_mode enclosed
set_clock_uncertainty 1 [get_clocks {clk}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb2}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb1}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb4}]
